gem 'activeresource', " >= 2.3.8"
require 'active_resource'
$:.unshift(File.dirname(__FILE__))

require 'highrise/base'
require 'highrise/pagination'
require 'highrise/taggable'
require 'highrise/subject'
require 'highrise/comment'
require 'highrise/company'
require 'highrise/email'
require 'highrise/group'
require 'highrise/kase'
require 'highrise/membership'
require 'highrise/note'
require 'highrise/person'
require 'highrise/task'
require 'highrise/user'
require 'highrise/tag'
require 'highrise/deal'
require 'highrise/account'
require 'highrise/deal_category'