require 'active_resource'

require File.dirname(__FILE__) + '/highrise/base'
require File.dirname(__FILE__) + '/highrise/pagination'
require File.dirname(__FILE__) + '/highrise/taggable'
require File.dirname(__FILE__) + '/highrise/subject'
require File.dirname(__FILE__) + '/highrise/comment'
require File.dirname(__FILE__) + '/highrise/company'
require File.dirname(__FILE__) + '/highrise/email'
require File.dirname(__FILE__) + '/highrise/group'
require File.dirname(__FILE__) + '/highrise/kase'
require File.dirname(__FILE__) + '/highrise/membership'
require File.dirname(__FILE__) + '/highrise/note'
require File.dirname(__FILE__) + '/highrise/person'
require File.dirname(__FILE__) + '/highrise/task'
require File.dirname(__FILE__) + '/highrise/user'
require File.dirname(__FILE__) + '/highrise/tag'
